### ISSUE TITLE
files loaded in this package became html

### ISSUE THREAD

**Issue by davidlange6** [cms-data/SLHCUpgradeSimulations-Geometry#1]
@degano - it looks like something went wrong when you created the files in this directory - they should be text not html. Can you have a look?

**Comment by ghost** [comment]
@boudoul, @davidlange6 tells me that you might know where the original files are stored. Could you please point me -again- at them so I can fix this issue?

**Comment by boudoul** [comment]
hi @degano ,
I put the original files in  /afs/cern.ch/user/b/boudoul/public/forAlessandro/ 
to be more precise : 

https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/blob/master/PhaseII/Flat/PixelSkimmedGeometry.txt
shoud be replaced by /afs/cern.ch/user/b/boudoul/public/forAlessandro/Flat/PixelSkimmedGeometry.txt

the file https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/blob/master/PhaseII/Tilted/PixelSkimmedGeometry.txt
should be replaced by  /afs/cern.ch/user/b/boudoul/public/forAlessandro/Tilted/PixelSkimmedGeometry.txt

Thanks!

**Comment by boudoul** [comment]
thanks @degano !
